### ISSUE TITLE
Business Logic research and design

### ISSUE THREAD

**Issue by wxtestelle** [StarRUC/HappyTimeRestaurant#10]

**Comment by Dorajia** [comment]
Sign up/Login/Log out
           user need account name, password, phone number, email address to sign in
           user need account name and password to login

Menu Display
          Menu will display in catalog(starter, main course, noodle, rice, beverage, dessert, soup).
          Each dish should show picture, name, price, materia
          The menu will display in the main page for use scan, but it has order button, once user click on the order button, the user will need to login first and select the location(zipcode), then the user will go to an order page. Display and order page is not the same one.       

Shopping Cart/Order related/Payment
         In order page, every dish has “Add to shopping cart” button, once user click on add to shopping cart, the dish will be saved in the shopping cart. After user has selected all the items, he goes to the shopping cart to check his dishes.
        In shopping cart page, the user will see all the dishes he selected and the total price, also the recommended dishes. User can select the recommended dishes into the order or delete the unwanted items from the shopping cart.
       After user has confirmed that he wants to check out, he will click on check out and user will be asked to enter the address and contact information, after user finish it, user will go to the checkout page.  
      In the checkout page, the order details(orders, delivery address, contact number) will show up and user can select different ways to check out(credit card, cash).

Recommendation Dishes
            Part 1: Main page should have special dishes for today.
            Part 2: In the shopping cart page, user will see the recommendation dishes. If there is no beverage, soup or dessert in the user’s order, we will recommend the corresponding items, user can just add them into the order and proceed to checkout.

Comments on dishes?
           User needs to confirm he received the delivery in the order history. After user confirms, he is able to go to his order history and put comment on the dishes.
          If we have comments, then in the order page, every dish needs to have a comment button or total score (stars or something) and once click on the comment button, the comment page for the dishes will show up and display all the comments made by users for this dishes.

User Profile
           The user’s sign in  information, delivery address,  order history should be saved.

Tracker?
Couple/gift cards/gift point?
Branch management?
